# Generated by Django 2.2.1 on 2021-02-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='prodescrip',
            field=models.TextField(),
        ),
    ]
